export const REGISTER_LIST_FAIL = "REGISTER_LIST_FAIL";
export const REGISTER_LIST_ADD_SUCCESS = "REGISTER_LIST_ADD_SUCCESS";
export const REGISTER_LIST_DELETE_SUCCESS = "REGISTER_LIST_DELETE_SUCCESS";
export const REGISTER_LIST_EDIT_SUCCESS = "REGISTER_LIST_EDIT_SUCCESS";
export const ALL_REGISTER = "ALL_REGISTER";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOG_IN_OK = "LOG_IN_OK";
export const LOG_IN_FAIL = "LOG_IN_FAIL";


export const TEST_SUBBMIT = "TEST_SUBBMIT"
export const TEST_EDIT = "TEST_EDIT"
export const TEST_DELETE = "TEST_DELETE"
export const OPERTION_FAIL = "OPERTION_FAIL"
export const GET_ALL_TEST = "GET_ALL_TEST"
export const GET_ONE_TEST = "GET_ONE_TEST"


export const SELECTED_TESTS = "SELECTED_TESTS"
export const SUBBMIT_TEST = "SUBBMIT_TEST"
export const OPERTION_TEST_FAIL = "OPERTION_TEST_FAIL"

